# If this shell is not interactive, don't do anything.
[[ $- != *i* ]] && return

source ~/.bash_aliases
source ~/.git-completion.bash
source ~/.git-prompt.sh
[ -f ~/reservoir/bash/bash_reservoir ] && source ~/reservoir/bash/bash_reservoir

# Shells inside Emacs print a prompt for each file sourced. Source this file
# last as a work around.
source ~/.bash_prompt

# Increase the size of the  history file.
HISTFILESIZE=3000
# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# Time stamp commands in the history file.
HISTTIMEFORMAT="%F %T "
# Append to the history file, don't overwrite it.
shopt -s histappend

# Don't try to complete an empty command.
shopt -s no_empty_cmd_completion

# Add an alias for setting raw mouse input on OS X.
alias raw-mouse="defaults write .GlobalPreferences com.apple.mouse.scaling -1"

# If PROJECT is empty, just use the builtin cd. If PROJECT is not empty, with no
# arguments, cd to the project root. Otherwise, cd without following symlinks
# and without standard output.
cd() {
    if [ -z "$PROJECT" ]; then
        command cd "$@"
        return
    fi

    if [ "$#" -eq 0 ]; then
        command cd "${PROJECT#*:}"
    else
        command cd -P "$@" >/dev/null
    fi
}
