[ -f ~/.bashrc ] && source ~/.bashrc

if [ $(uname) != Darwin ]; then
    # Check for an ssh-agent. If there isn't one, start one.
    SSH_AGENT_PID=$(pgrep -u $USER ssh-agent)
    if [ "$SSH_AGENT_PID" ]; then
        export SSH_AGENT_PID
        export SSH_AUTH_SOCK=~/.ssh/ssh-agent-socket
    else
        eval $(ssh-agent -a ~/.ssh/ssh-agent-socket)
    fi
fi

# Add my bin to path.
PATH=$HOME/bin:$PATH

# Set my default editor to emacs. Don't set desktop-save-mode, don't use a
# window system, and don't confirm killing these sessions.
#
# NB: Using a \ before a new line causes issues, so just use += instead.
EDITOR='emacs --no-desktop --no-window-system '
EDITOR+='--eval "(setq confirm-kill-emacs nil)"'

# Set default less options--turn off the terminal bell, display raw control
# characters for ANSI color escape sequences, and ignore case in search.
LESS='RQi'

export PATH EDITOR LESS

# Turn off the bash deprecation warning on Catalina.
export BASH_SILENCE_DEPRECATION_WARNING=1
