# ~/.bash_aliases
# George Whiteside

# Use colors when appropriate and, if supported, ignore backup files in ls.
if [ "$(uname)" == Darwin ]; then
    alias ls='ls -G'
    alias la='ls -AG'
else
    alias ls='ls --color=auto --hide="*~" --hide="*#"'
    alias la='ls -A --color=auto'
fi

# Not all distros have an rgrep.
type rgrep &> /dev/null || alias rgrep='grep -r'

# Shut up gdb.
alias gdb='gdb -q'

# Alias shutdown and restart.
alias shutdown='shutdown now'
alias restart='shutdown -r now'
