[ -f ~/.bashrc ] && source ~/.bashrc

# If ccache is installed, add the standard ccache drivers to PATH.
type ccache &>/dev/null && PATH=/usr/lib/ccache:$PATH

# Add my bin to path.
PATH=$HOME/bin:$PATH

# Set my default editor to emacsclient. If a server isn't available, then start
# emacs without loading a saved desktop or a window system and don't confirm
# killing the session. If emacs isn't installed, just use vim.
#
# NB: Using a \ before a new line causes issues, so just use += instead.
if type emacs &>/dev/null; then
    ALTERNATE_EDITOR='emacs --no-desktop --no-window-system '
    ALTERNATE_EDITOR+='--eval "(setq confirm-kill-emacs nil)"'

    # Output stderr to /dev/null to silence warning.
    EDITOR="emacsclient --tty 2>/dev/null"
else
    EDITOR=vim
fi

# Set default less options--turn off the terminal bell, display raw control
# characters for ANSI color escape sequences, and ignore case in search.
LESS='RQi'

# If the current terminal is dumb, set the pager to cat. If the terminal isn't
# dumb and diff-highlight can't be found, set GIT_PAGER to the value of
# core.pager so that the pager.<cmd> settings are ignore.
if [ "$TERM" = "dumb" ]; then
    GIT_PAGER='cat'
elif ! type diff-highlight &>/dev/null; then
    GIT_PAGER="$(git config --global core.pager)"
fi

export PATH ALTERNATE_EDITOR EDITOR LESS GIT_PAGER

# Turn off the bash deprecation warning on Catalina.
export BASH_SILENCE_DEPRECATION_WARNING=1
