# ~/.bash_profile
# George Whiteside

[ -f ~/.bashrc ] && source ~/.bashrc

# Add my bin to path.
PATH=$HOME/bin:$PATH

# Set my default editor to emacs. Don't set desktop-save-mode, don't use a
# window system, and don't confirm killing these sessions.
EDITOR='emacs --no-desktop --no-window-system'
EDITOR+=' --eval "(setq confirm-kill-emacs nil)"'

# Set my default less options--turn off bell and ignore case in search.
LESS='RQi'

# Set default grep options.
GREP_OPTIONS='--color=auto --binary-files=without-match --directories=skip'
GREP_OPTIONS+=' --exclude=*~ --exclude=*# --exclude-dir=.git'

export PATH EDITOR LESS GREP_OPTIONS

# Turn off the bash deprecation warning on Catalina.
export BASH_SILENCE_DEPRECATION_WARNING=1
