# Use colors when appropriate and, if supported, ignore backup files while
# using ls.
if [ "$(uname)" = Darwin ]; then
    alias ls='ls -G'
    alias la='ls -AG'
else
    alias ls='ls --color=auto --hide="*~" --hide="*#"'
    alias la='ls -A --color=auto'
fi

# Shut up gdb.
alias gdb='gdb -q'

# Shorten less to l.
alias l='less'

# Set default grep options.
grep_options='--color=auto --binary-files=without-match \
--exclude=*~ --exclude=*# --exclude-dir=.git'
alias grep="grep --directories=skip ${grep_options}"
alias rgrep="grep --directories=recurse ${grep_options}"
alias rgrep-cmake="grep --directories=recurse --include='[Cc][Mm]ake*' \
${grep_options}"
