#!/bin/bash

# Installs config files and some scripts and configures git for this repo.
# Should be run from the project root.
#
# Usage: install [OPTION]...
#
# Options are passed directly to ln (see man ln). Some useful options are
# --force and --interactive.

config=$PWD

if [[ "$config" != *"$HOME"* ]]; then
    echo "This config can only be installed from inside your HOME directory."
    exit 1
fi


## Dotfiles

# Symlink dotfiles to home directory, adding a leading dot.
for dotfile in $config/dotfiles/* ; do
    ln --symbolic "$@" $dotfile ~/.${dotfile##*/}
done


## Emacs
ln --symbolic "$@" $config/emacs.d ~/.emacs.d

## SSH
# Set the permissions for the ssh config. It must be read/write
# for the user, and not writable by others.
chmod 644 $config/ssh/config

# Symlink the ssh directory to .ssh.
ln --symbolic "$@" $config/ssh ~/.ssh
