#!/bin/bash

# Installs config files and some scripts and configures git for this repo.
# Should be run from the project root.
#
# Usage: install [OPTION]...
#
# Options are passed directly to ln (see man ln). Some useful options are
# --force and --interactive.

config=$PWD

## Dotfiles
# Symlink dotfiles to home directory, adding a leading dot.
for dotfile in $config/dotfiles/* ; do
    ln -s "$@" $dotfile ~/.${dotfile##*/}
done


## Emacs
ln -s "$@" $config/emacs.d ~/.emacs.d

## SSH
# Set the permissions for the ssh config. It must be read/write
# for the user, and not writable by others.
chmod 644 $config/ssh/config

# Symlink the ssh directory to .ssh.
ln -s "$@" $config/ssh ~/.ssh
