#!/bin/bash
# Pulls config files from system to this repo

files=$(ls -1A --ignore=pull* --ignore=push* --ignore=install* --ignore=.git)
pwd=$(pwd)
cd ~
for file in $files; do
  if [ -f $file ]; then
    cp $file $pwd
  fi
  echo $file
done
cd $pwd
